--[[My Discord For Help Houman#7172]]--[[My Discord For Help Houman#7172]]
--[[My Discord For Help Houman#7172]]--[[My Discord For Help Houman#7172]]
--[[My Discord For Help Houman#7172]]--[[My Discord For Help Houman#7172]]
--[[My Discord For Help Houman#7172]]--[[My Discord For Help Houman#7172]]
--[[My Discord For Help Houman#7172]]--[[My Discord For Help Houman#7172]]

--[[Hu_Leak : https://discord.gg/2AQCXpbv95 ]]
                --[[ Houman ]]                 
--[[Hu_Leak : https://discord.gg/2AQCXpbv95 ]]

--[[ Hu_Badges_list = { { serverid, job, name, color } } ]]
local Hu_Badges_list = {} RegisterNetEvent('Hu_Badges:ADD') AddEventHandler("Hu_Badges:ADD", function(serverid, jobname, nameconfig, color) if GetCurrentResourceName() == "Hu_Badges" then else return end local fined = false for o,i in pairs(Hu_Badges_list) do--[[My Discord For Help Houman#7172]]
if i[1] ~= nil then if tonumber(i[1]) == tonumber(GetPlayerFromServerId(serverid)) then print(color) table.insert(Hu_Badges_list, {serverid, jobname, nameconfig, {r=color[1], g=color[2], b=color[3]}}) fined = true table.remove(Hu_Badges_list, o) end--[[My Discord For Help Houman#7172]]
end end if not fined then table.insert(Hu_Badges_list, {serverid, jobname, nameconfig, {r=color[1], g=color[2], b=color[3]}})--[[My Discord For Help Houman#7172]]
end end) Citizen.CreateThread(function() while true do Citizen.Wait(1) if Hu_Badges_list ~= nil then local no_pepol = false for o,s in pairs(Hu_Badges_list) do--[[My Discord For Help Houman#7172]]
for i = 0, Config.AllPlayers do if tonumber(GetPlayerServerId(i)) == tonumber(s[1]) then if NetworkIsPlayerActive(i) then local ped = GetPlayerPed(i) local id = GetPlayerServerId(i) local name = GetPlayerName(i) if ped ~= nil and id ~= nil and name ~= nil then no_pepol = true--[[My Discord For Help Houman#7172]]
if Vdist2(GetEntityCoords(ped, false), GetEntityCoords(PlayerPedId(), false)) <= 15 then local head_coords = GetEntityBonePosition_2(ped, GetEntityBoneIndexByName(ped, "IK_Head")) if Vdist2(GetEntityCoords(ped, false), GetEntityCoords(PlayerPedId(), false)) <= 10 then DrawText3D(head_coords.x, head_coords.y, head_coords.z + Config.up_head, s[2] .. " | " .. s[3], s[4].r, s[4].g,  s[4].b, 255)--[[My Discord For Help Houman#7172]]
else DrawText3D(head_coords.x, head_coords.y, head_coords.z + Config.up_head, s[2] .. " | " .. s[3], s[4].r, s[4].g,  s[4].b, 150)--[[My Discord For Help Houman#7172]]
end end end end end end end if not no_pepol then Citizen.Wait(2500) end else--[[My Discord For Help Houman#7172]]
Citizen.Wait(2500) end end end) RegisterNetEvent('Hu_Badges:Remove') AddEventHandler("Hu_Badges:Remove", function(serverid) if GetCurrentResourceName() == "Hu_Badges" then else return end local k = 0 local deleteed = false for o,i in pairs(Hu_Badges_list) do k = k + 1 if i[1] ~= nil then for s = 0, Config.AllPlayers do--[[My Discord For Help Houman#7172]]
if tonumber(GetPlayerServerId(s)) == tonumber(i[1]) then deleteed = true print(i[1]) table.remove(Hu_Badges_list, o) break end end end end  if GetCurrentResourceName() == "Hu_Badges" then else return end if k <= 1 and deleteed then Hu_Badges_list = {}--[[My Discord For Help Houman#7172]]
end end) DrawText3D = function(x, y, z, text, r, g, b, a) lx = x ly = y lz = z if text == nil then text = ' ' end--[[My Discord For Help Houman#7172]]
local onScreen,x,y = World3dToScreen2d(x, y, z) mk = GetEntityCoords(GetPlayerPed(-1), true) local xx = 0 local yy = 0 local zz = 0 if mk.x > lx then xx = mk.x - lx else xx = lx - mk.x end--[[My Discord For Help Houman#7172]]
if mk.y > ly then yy = mk.y - ly else yy = ly - mk.y end if mk.z > lz then zz = mk.z - lz else zz = lz - mk.z end ll = ( zz + xx + yy )--[[My Discord For Help Houman#7172]]
local factor = (0.5 * 2) / ll if ll <= 3.0 then factor = 0.7 end if ll <= 120.0 then SetTextScale(factor, factor) SetTextFont(4) SetTextProportional(1) SetTextColour(r, g, b, a) SetTextEntry("STRING") SetTextCentre(1) AddTextComponentString(text) DrawText(x,y) end end if GetCurrentResourceName() == "Hu_Badges" then else return end TriggerEvent('chat:addSuggestion', '/' .. Config.ToggleBadgeJobsCommand, Config.ToggleBadgeJobsCommandinfo, {})--[[My Discord For Help Houman#7172]]

--[[Hu_Leak : https://discord.gg/2AQCXpbv95 ]]
                --[[ Houman ]]                 
--[[Hu_Leak : https://discord.gg/2AQCXpbv95 ]]

--[[My Discord For Help Houman#7172]]--[[My Discord For Help Houman#7172]]
--[[My Discord For Help Houman#7172]]--[[My Discord For Help Houman#7172]]
--[[My Discord For Help Houman#7172]]--[[My Discord For Help Houman#7172]]
--[[My Discord For Help Houman#7172]]--[[My Discord For Help Houman#7172]]
